name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
